CREATE TABLE IF NOT EXISTS reports(date TEXT PRIMARY KEY, status TEXT NOT NULL, stage TEXT NOT NULL, title TEXT NOT NULL, reason TEXT NOT NULL, last_event TEXT, payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS runs(id TEXT PRIMARY KEY, date TEXT NOT NULL REFERENCES reports(date), payload TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS events(run_id TEXT NOT NULL REFERENCES runs(id), seq INTEGER NOT NULL, digest TEXT NOT NULL, payload TEXT NOT NULL, PRIMARY KEY(run_id,seq));
CREATE TABLE IF NOT EXISTS notes(id INTEGER PRIMARY KEY, date TEXT NOT NULL REFERENCES reports(date), body TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY, action TEXT NOT NULL, target TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY, csrf TEXT NOT NULL, expires REAL NOT NULL);
CREATE TABLE IF NOT EXISTS meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS runs_date ON runs(date);
PRAGMA user_version=1;
