export interface HistoricalCover {
  src: string
  title: string
  sourceUrl: string
  attribution: string
  license: string
}

export const HISTORICAL_COVERS: HistoricalCover[] = [
  {
    src: "/covers/historical/met-01-landscape-with-a-double-spruce.jpg",
    title: "Landscape with a Double Spruce",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/336259",
    attribution: "Albrecht Altdorfer",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-02-landscape.jpg",
    title: "Landscape",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/386043",
    attribution: "François Jean Sablet",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-03-landscape.jpg",
    title: "Landscape",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/720025",
    attribution: "Alexandre Calame",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-04-landscape.jpg",
    title: "Landscape",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/385236",
    attribution: "Hermanus Fock",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-05-landscape.jpg",
    title: "Landscape",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/765254",
    attribution: "Jean-Baptiste-Claude Chatelain",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-06-landscape.jpg",
    title: "Landscape",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/765250",
    attribution: "Jean-Baptiste-Claude Chatelain",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-07-landscape.jpg",
    title: "Landscape",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/692483",
    attribution: "Adolphe Balfourier",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-08-landscape.jpg",
    title: "Landscape",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/909240",
    attribution: "Elbridge Kingsley",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-09-landscape.jpg",
    title: "Landscape",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/690986",
    attribution: "Goya (Francisco de Goya y Lucientes)",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-10-naues-mercatori-hollandic-per-indias-occ.jpg",
    title: "Naues Mercatoriæ Hollandicæ per Indias Occidentales (Dutch West Indiaman)",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/361531",
    attribution: "Wenceslaus Hollar",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-11-naues-mercatori-hollandic-per-indias-occ.jpg",
    title: "Naues Mercatoriæ Hollandicæ per Indias Occidentales (Dutch East Indiaman)",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/361530",
    attribution: "Wenceslaus Hollar",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-12-storm.jpg",
    title: "Storm",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/765093",
    attribution: "Jean-Baptiste-Claude Chatelain",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-13-a-yacht-and-three-warships-in-a-storm.jpg",
    title: "A yacht and three warships in a storm",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/361766",
    attribution: "Wenceslaus Hollar",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-14-sea-storms.jpg",
    title: "Sea Storms",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/361765",
    attribution: "Wenceslaus Hollar",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-15-warship-in-the-trough-of-a-wave.jpg",
    title: "Warship in the Trough of a Wave",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/361510",
    attribution: "Wenceslaus Hollar",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-16-architecture-arabe-ou-monuments-du-kaire.jpg",
    title: "Architecture arabe : ou, Monuments du Kaire, mesurés et dessinés, de 1818 à 1826",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/811182",
    attribution: "Pascal Coste",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-17-classical-ruins.jpg",
    title: "Classical Ruins",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/360633",
    attribution: "Wenceslaus Hollar",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-18-ruins-and-a-barred-gate-on-the-esquiline.jpg",
    title: "Ruins and a barred gate on the Esquiline Hill in Rome, from \"Roman Ruins\"",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/360674",
    attribution: "Wenceslaus Hollar",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-19-boats-rowed-through-inundated-ruins.jpg",
    title: "Boats Rowed Through Inundated Ruins",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/399622",
    attribution: "Virgil Solis",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-20-riverscape-with-ruins-of-a-castle-from-l.jpg",
    title: "Riverscape with Ruins of a Castle, from \"Landscapes and Ruins\"",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/398942",
    attribution: "Jan van de Velde II",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-21-plate-13-ruins-of-an-ancient-temple-in-t.jpg",
    title: "Plate 13: ruins of an ancient temple in the background, a herd of cows in the foreground, from \"Roman landscapes and ruins\" (Paysages et ruines de Rome)",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/413360",
    attribution: "Stefano della Bella",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-22-vauxhall-bridge.jpg",
    title: "Vauxhall Bridge",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/372524",
    attribution: "James McNeill Whistler",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-23-windsor-castle.jpg",
    title: "Windsor Castle",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/360854",
    attribution: "Wenceslaus Hollar",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-24-the-castle.jpg",
    title: "The Castle",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/398946",
    attribution: "Jan van de Velde II",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-25-forest-landscape.jpg",
    title: "Forest Landscape",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/394478",
    attribution: "Domenico Quaglio II",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-26-stags-in-the-forest.jpg",
    title: "Stags in the Forest",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/730797",
    attribution: "Augustin Hirschvogel",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-27-mountain-valley-with-a-plateau.jpg",
    title: "Mountain Valley with a Plateau",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/359882",
    attribution: "Hercules Segers",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-28-river-valley-with-obelisk.jpg",
    title: "River Valley with Obelisk",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/349357",
    attribution: "Lucas Gassel",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-29-a-stream-in-the-mondois-valley.jpg",
    title: "A Stream in the Mondois Valley",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/337014",
    attribution: "Charles-François Daubigny",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-30-moonrise-in-the-valley-of-the-andilly.jpg",
    title: "Moonrise in the Valley of the Andilly",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/336853",
    attribution: "Charles-François Daubigny",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-31-the-town-hostel.jpg",
    title: "The Town Hostel",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/381310",
    attribution: "Reinier Nooms, called Zeeman",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-32-the-town-wall-of-regensberg.jpg",
    title: "The Town Wall of Regensberg",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/368186",
    attribution: "Johann Christoph Erhard",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-33-a-boat-near-the-shoreline-of-a-beach-or-.jpg",
    title: "A boat near the shoreline of a beach or a river",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/660567",
    attribution: "Mariano Fortuny, 1838–1874",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-34-a-voice-from-the-cliff.jpg",
    title: "A Voice from the Cliff",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/727172",
    attribution: "Pierre Salvy Frédéric Teyssonnières",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-35-harbor-scene.jpg",
    title: "Harbor Scene",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/397355",
    attribution: "Ludolf Backhuysen",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-36-horses-in-the-meadow.jpg",
    title: "Horses in the Meadow",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/358802",
    attribution: "Edgar Degas",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-37-landscape-with-farmhouse.jpg",
    title: "Landscape with Farmhouse",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/397469",
    attribution: "Boetius Adams Bolswert",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-38-a-farmhouse-beside-the-water.jpg",
    title: "A Farmhouse Beside the Water",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/382803",
    attribution: "Anthonie Waterloo",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-39-landscape-with-a-farmhouse-along-a-road-.jpg",
    title: "Landscape with a Farmhouse Along a Road Beside a Canal",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/389436",
    attribution: "Rembrandt (Rembrandt van Rijn)",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-40-the-large-waterfall.jpg",
    title: "The Large Waterfall",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/370131",
    attribution: "Anthonie Waterloo",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-41-waterfall-after-breenberg.jpg",
    title: "Waterfall after Breenberg",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/395401",
    attribution: "Jean Jacques de Boissieu",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-42-the-dome-and-the-waterfall.jpg",
    title: "The Dome and the Waterfall",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/370133",
    attribution: "Anthonie Waterloo",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-43-group-of-people-looking-at-a-waterfall.jpg",
    title: "Group of People Looking at a Waterfall",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/385459",
    attribution: "Etienne de Lavallée-Poussin",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-44-peasants-and-a-mill.jpg",
    title: "Peasants and a Mill",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/399663",
    attribution: "Franz de Paula Ferg",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-45-a-path-through-the-woods.jpg",
    title: "A Path Through the Woods",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/382805",
    attribution: "Anthonie Waterloo",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-46-paths-in-the-dukedom-of-salzburg.jpg",
    title: "Paths in the Dukedom of Salzburg",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/368194",
    attribution: "Johann Christoph Erhard",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-47-view-near-albury.jpg",
    title: "View Near Albury",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/360941",
    attribution: "Wenceslaus Hollar",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-48-seaport-with-village-on-a-cliff.jpg",
    title: "Seaport with Village on a Cliff",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/380678",
    attribution: "Reinier Nooms, called Zeeman",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-49-the-cliff-bay-of-saint-malo.jpg",
    title: "The Cliff  - Bay of Saint-Malo",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/385978",
    attribution: "Félix-Hilaire Buhot",
    license: 'CC0 (The Met Open Access)',
  },
  {
    src: "/covers/historical/met-50-the-cliff-dwellers-of-new-york.jpg",
    title: "The Cliff Dwellers of New York",
    sourceUrl: "https://www.metmuseum.org/art/collection/search/368100",
    attribution: "Mary Nimmo Moran",
    license: 'CC0 (The Met Open Access)',
  },
]

export function getHistoricalCoverByIndex(index: number): HistoricalCover {
  return HISTORICAL_COVERS[((index % HISTORICAL_COVERS.length) + HISTORICAL_COVERS.length) % HISTORICAL_COVERS.length]
}
